version: "3"
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: somepassword
          MYSQL_DATABASE: AvayaCdr
          MYSQL_USER: cdruser
          MYSQL_PASSWORD: somepassword

        ports:
            - "3306:3306"  
        volumes:
            - .:/docker-entrypoint-initdb.d

    web:
        build: .
        ports:
            - "60010:60010"
        links: 
            - "db:database"
        restart: always
        depends_on:
            - db
